### PR TITLE
Disallow constructor in callHandlers.

### PR DESCRIPTION
**Pull request by fubhy**
Fixes https://github.com/graphprotocol/support/issues/8#issuecomment-492947577

### CODE REVIEW

**Comment by fubhy** [comment]
I think the tests just need a restart. The failure seems unrelated.

**Comment by Jannis** [comment]
Yep, the `graph auth` test failures are resolved on master.

**Comment by Jannis** [comment]
Yep, the `graph auth` test failures are resolved on master.

**Comment by Jannis** [comment]
We'll want to bring this back in some form later but for now we should remove it, as it isn't yet supported.

**Pull request merged**
