### PR TITLE
Generate schema code for `BigDecimal`

### PR DESCRIPTION
**Pull request by leodasvacas**
Needs to be tested with complete graph-ts support.

### CODE REVIEW

**Comment by Jannis** [comment]
@leodasvacas Hah, I actually meant tests here: https://github.com/graphprotocol/graph-cli/blob/master/src/codegen/types/index.test.js

**Comment by leodasvacas** [comment]
@Jannis added the codegen tests and fixed the dir name.

**Comment by leodasvacas** [comment]
@Jannis I can't merge because of CI, which is failing because the example subgraph's graph-ts doesn't have BigDecimal.

**Comment by Jannis** [comment]
Ah, that makes sense. Let's merge this now and update the example subgraph later when we're ready to release a new graph-ts (waiting for the struct/tuple support and `ipfs.map` being merged).

**Comment by Jannis** [comment]
I'll force merge it now. :godmode:

**Pull request merged**
