### PR TITLE
cli: Add getter methods to call return types

### PR DESCRIPTION
**Pull request by staa99**
Implements [#869](https://github.com/graphprotocol/graph-cli/issues/869).

### CODE REVIEW

**Comment by tilacog** [comment]
Seems like the unit tests passed but the CI errored at the `docker login` command.
This is an expected failure, as only members can have access to Travis' secrets.

**Comment by staa99** [comment]
Thanks for checking it out.

What do you think about the update?

**Comment by evaporei** [comment]
Hey @staa99 thanks for the contribution!!!

I agree that the developer experience can be improved, however I don't agree with the implementation.

The way this PR changes the code generation is appending `getters` at the end of a `Result` class:

```typescript
export class {{ABI_NAME}}__{{FN_ALIAS}}Result {
  value0: BigInt;
  value1: Address;
  value2: string;

  constructor(
    value0: BigInt,
    value1: Address,
    value2: string
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    map.set("value2", ethereum.Value.fromString(this.value2));
    return map;
  }

  // NEW CODE:

  getValue0(): BigInt {
    return this.value0;
  }

  getValue1(): Address {
    return this.value1;
  }

  getValue2(): string {
    return this.value2;
  }
}
```

However I think it would be simpler to just add a `public` modifier to those fields, like this:

```typescript
export class {{ABI_NAME}}__{{FN_ALIAS}}Result {
  public value0: BigInt;
  public value1: Address;
  public value2: string;

  constructor(
    value0: BigInt,
    value1: Address,
    value2: string
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    map.set("value2", ethereum.Value.fromString(this.value2));
    return map;
  }
}
```

Or even simplifying it even further, AssemblyScript supports a notation that the constructor can receive the `public` modifier itself, like this:


```typescript
export class {{ABI_NAME}}__{{FN_ALIAS}}Result {
  constructor(
    public value0: BigInt,
    public value1: Address,
    public value2: string
  ) {
    // doesn't require to set them! :)
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    map.set("value2", ethereum.Value.fromString(this.value2));
    return map;
  }
}
```

Unfortunately our ["typescript" code generation](https://github.com/graphprotocol/graph-cli/blob/main/src/codegen/typescript.js#L73) currently doesn't support any of those, so you would have to change that instead.

What do you think? 🙂

**Comment by staa99** [comment]
Hi @evaporei 

Thank you very much for your review. I think it's necessary for me to add more context here. I'll create a scenario:

Assuming the following contract exists:

````Solidity
contract SampleContract {
  struct A {
    uint256 someNumber;
    address someAddress;
  }
  
  function getData() public returns(A memory) {
    return A(block.timestamp, msg.sender);
  }
}
````

The code generator will generate a class like the following:

````TypeScript
export class {{ABI_NAME}}__{{FN_ALIAS}}Result {
  value0: BigInt;
  value1: Address;

  constructor(
    value0: BigInt,
    value1: Address
  ) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    return map;
  }
}
````

This is the current behavior. My changes will cause the generated class to change to this:

````TypeScript
export class {{ABI_NAME}}__{{FN_ALIAS}}Result {
  value0: BigInt;
  value1: Address;

  constructor(
    value0: BigInt,
    value1: Address
  ) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    return map;
  }

  getSomeNumber(): BigInt {
    return this.value0;
  }

  getSomeAddress(): Address {
    return this.value1;
  }
}
````

It is more friendly to use `getSomeNumber()` and `getSomeAddress()` in code than use the `value0` and `value1` fields. That's why I implemented it this way. What do you think? 🙂

**Comment by evaporei** [comment]
@staa99 the code I've posted above was generated with your branch, I don't see how it would generate methods with the names `getSomeNumber` and `getSomeAddress` in the name instead of `getValue0` and `getValue1`, could you elaborate on that please? 🙂

**Comment by staa99** [comment]
Sure @evaporei. The reason why it generated those for you is because of the names of the variables in your ABI. The line `get${output.get('name')[0].toUpperCase()}${output.get('name').slice(1)}` reads the name of the variable from the ABI, capitalizes the first letter and prepends `get` to it. For example, `feeRate` becomes `getFeeRate`.


I'll use a real sample I have locally. I updated my local implementation (in node_modules) to use the feature.

I have an abi with these fields:

````json
{
  "inputs": [
    {
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
    }
  ],
  "name": "sellOrders",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "id",
      "type": "uint256"
    },
    {
      "internalType": "uint256",
      "name": "totalAmount",
      "type": "uint256"
    },
    {
      "internalType": "uint256",
      "name": "feeRate",
      "type": "uint256"
    },
    {
      "internalType": "uint256",
      "name": "minimumBuyAmount",
      "type": "uint256"
    },
    {
      "internalType": "uint256",
      "name": "lockedAmount",
      "type": "uint256"
    },
    {
      "internalType": "uint256",
      "name": "filledAmount",
      "type": "uint256"
    },
    {
      "internalType": "uint32",
      "name": "preDisputeDuration",
      "type": "uint32"
    },
    {
      "internalType": "address",
      "name": "seller",
      "type": "address"
    },
    {
      "internalType": "address",
      "name": "token",
      "type": "address"
    },
    {
      "internalType": "bool",
      "name": "active",
      "type": "bool"
    },
    {
      "internalType": "bytes",
      "name": "metadataURI",
      "type": "bytes"
    }
  ],
  "stateMutability": "view",
  "type": "function"
}
````

It generates the following class without the getters:

````TypeScript
export class CryptoExchange__sellOrdersResult {
  value0: BigInt;
  value1: BigInt;
  value2: BigInt;
  value3: BigInt;
  value4: BigInt;
  value5: BigInt;
  value6: BigInt;
  value7: Address;
  value8: Address;
  value9: boolean;
  value10: Bytes;

  constructor(
    value0: BigInt,
    value1: BigInt,
    value2: BigInt,
    value3: BigInt,
    value4: BigInt,
    value5: BigInt,
    value6: BigInt,
    value7: Address,
    value8: Address,
    value9: boolean,
    value10: Bytes
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
    this.value6 = value6;
    this.value7 = value7;
    this.value8 = value8;
    this.value9 = value9;
    this.value10 = value10;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    map.set("value2", ethereum.Value.fromUnsignedBigInt(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    map.set("value4", ethereum.Value.fromUnsignedBigInt(this.value4));
    map.set("value5", ethereum.Value.fromUnsignedBigInt(this.value5));
    map.set("value6", ethereum.Value.fromUnsignedBigInt(this.value6));
    map.set("value7", ethereum.Value.fromAddress(this.value7));
    map.set("value8", ethereum.Value.fromAddress(this.value8));
    map.set("value9", ethereum.Value.fromBoolean(this.value9));
    map.set("value10", ethereum.Value.fromBytes(this.value10));
    return map;
  }

  getId(): BigInt {
    return this.value0;
  }

  getTotalAmount(): BigInt {
    return this.value1;
  }

  getFeeRate(): BigInt {
    return this.value2;
  }

  getMinimumBuyAmount(): BigInt {
    return this.value3;
  }

  getLockedAmount(): BigInt {
    return this.value4;
  }

  getFilledAmount(): BigInt {
    return this.value5;
  }

  getPreDisputeDuration(): BigInt {
    return this.value6;
  }

  getSeller(): Address {
    return this.value7;
  }

  getToken(): Address {
    return this.value8;
  }

  getActive(): boolean {
    return this.value9;
  }

  getMetadataURI(): Bytes {
    return this.value10;
  }
}
````

The problem is that it is hard to determine what the variables represent by using `value0` or `valueN`. With the getters, it's easy to work normally with little risk of bugs resulting from inadvertently using the wrong variable.

**Comment by staa99** [comment]
Hi @evaporei, thanks a lot for your review. What are the necessary steps to get the changes merged and what is the release cycle like?

**Comment by evaporei** [comment]
I'm sorry @staa99 that I didn't get back to this, I'll try to soon 🙏 

Again, thanks a lot for the contribution and proactiveness ❤️

**Comment by staa99** [comment]
Thanks a lot @evaporei. I appreciate the time taken to review the changes. I look forward to doing more to improve the tools we use and love.

**Comment by evaporei** [comment]
@staa99 sorry for the long await, I was OOO (out of office). Can you rebase your branch with `master` so we can merge it 🙂

**Comment by staa99** [comment]
Hi @evaporei,

Sorry about the late response. I'll do that today and leave a comment.

Thank you.

**Comment by staa99** [comment]
Hi @evaporei,
I have rebased my branch with `master`.
Thank you for your time.

**Pull request merged**
