### PR TITLE
Add Fuji to ABI loaders

### PR DESCRIPTION
**Pull request by schmidsi**
@incrypto32 Can you please test this?

https://github.com/graphprotocol/graph-cli/issues/874

### CODE REVIEW

**Comment by incrypto32** [comment]
@schmidsi Tested succesfully working perfectly. 
Screenshot 2022-05-24 at 11 41 43 AM

**Comment by schmidsi** [comment]
@evaporei please quickly review and merge

**Review by evaporei — CHANGES_REQUESTED** [review]
This just needs a rebase with `main` 🙂

**Comment by schmidsi** [comment]
Combined in this PR: https://github.com/graphprotocol/graph-cli/pull/909

**Pull request closed without merging**
