### PR TITLE
Add support for data source templates

### PR DESCRIPTION
**Pull request by Jannis**
This covers the Graph CLI changes required for dynamic data sources (see https://github.com/graphprotocol/graph-node/issues/719 for the design and plan).

Specifically, this adds

* Parsing and validation of data source templates in manifest,
* Code generation for data sources templates, and
* Building and deploying of data source template mappings.

### CODE REVIEW

**Comment by leodasvacas** [comment]
Your last commit says "WIP".

**Comment by Jannis** [comment]
@leodasvacas Updated, I had to rebase a little and squash a few things together.

**Comment by leodasvacas** [comment]
@Jannis Tests need updating.

**Comment by Jannis** [comment]
@leodasvacas Tests updated!

**Comment by Jannis** [comment]
Yep, I totally agree. Maybe one day we can rewrite this in Rust 😁

**Pull request merged**
