### PR TITLE
fix: basic auth

### PR DESCRIPTION
**Pull request by islishude**
There is no auth field in URL.

```js
new URL('https://:password@example.com/path');
URL {
  href: 'https://:password@example.com/path',
  origin: 'https://example.com',
  protocol: 'https:',
  username: '',
  password: 'password',
  host: 'example.com',
  hostname: 'example.com',
  port: '',
  pathname: '/path',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

### CODE REVIEW

**Review by evaporei — APPROVED** [review]
Thanks for the contribution @islishude !!

**Comment by air3ijai** [comment]
@islishude, does this code fix basic auth for IPFS endpoint as well?

I did some tests and got the following results
### Graph build - :x:
```bash
yarn graph build subgraph.yaml --ipfs https://user:pass@ipfs.domain.tld

✖ Failed to upload subgraph to IPFS: Failed to upload file to IPFS: Server responded with 404
```

This is reply from IPFS node and it means that same credentials works correctly with curl
```bash
curl https://user:pass@ipfs.domain.tld

404 page not found
```

### Graph create - :white_check_mark:
```bash
yarn graph create subgraph.yaml --node https://user:pass@rinkeby.index.domain.tld

Created subgraph: subgraph-test
```

### Graph deploy - :x:
```bash
yarn graph deploy subgraph-test subgraph.yaml \
  --version-label subgraph-test \
  --ipfs https://user:pass@ipfs.domain.tld \
  --node https://user:pass@rinkeby.index.domain.tld

✖ Failed to upload subgraph to IPFS: Failed to upload file to IPFS: Server responded with 404
```

Does your code fix basic authentication for IPFS node?

**Comment by islishude** [comment]
No, its used for grpah node jsonrpc

**Comment by islishude** [comment]
No, it's used for jsonrpc

you can also make a PR for ipfs

https://github.com/graphprotocol/graph-cli/blob/main/src/command-helpers/compiler.js#L22-L29

**Pull request merged**
