### PR TITLE
Use better the Node.js async API

### PR DESCRIPTION
**Pull request by otaviopace**
By reading this project code I was intrigued that a lot of IO operations were using synchronous APIs. Then, I searched for every `Sync` in here and tried to look were the function was used to check if it could use the `Async` version instead.

You might think/ask: why do this change?

It's not guaranteed to have performance improvements with this PR, **however**, by using Node.js asynchronous APIs, we can make sure we are at least giving to the "engine" all the information it needs to do other work while some code is waiting for IO.

### CODE REVIEW

**Comment by leoyvens** [comment]
Nice, tests are failing though.

**Comment by otaviopace** [comment]
Oops haha, I hope it's fixed now!

**Comment by otaviopace** [comment]
Oh no, it failed again, I'm gonna iterate until it's fixed 😅

**Comment by otaviopace** [comment]
Okay now it's fixed. Once [this](https://github.com/graphprotocol/graph-cli/pull/676) gets merged I will rebase 🙂

**Comment by schmidsi** [comment]
https://github.com/graphprotocol/graph-cli/pull/676 is merged ;)

**Comment by otaviopace** [comment]
@leoyvens the CI is finally fixed, whenever you can review again it would be great 🙂

**Review by leoyvens — APPROVED** [review]

**Pull request merged**
