### PR TITLE
Best practices for subgraph initialisation

### PR DESCRIPTION
**Pull request by schmidsi**
With these changes I want to make sure that newly initialised subgraphs follow best practices:
- Latest `specVersion` and `abiVersion`
- Using Bytes as IDs
- Immutable entities for events
- Auto-generated event entities enriched with `blockNumber`, ~`blockHash`~, `blockTimestamp`, `transactionHash` and ~`logIndex`~ to have a more powerful boilerplate
- Ask for index events during init-dialog
`✔ Index contract events as entities (Y/n) · true`

### CODE REVIEW

**Review by evaporei — APPROVED** [review]
Thank you a lot for updating the examples and using `Bytes` as `ID` :pray: 

And also for the clean up in the codebase :heart:

**Comment by evaporei** [comment]
Oh I just saw that the CI is failing on a test, can you rebase and try again? I think there's probably something you'll have to change.

**Comment by azf20** [comment]
@schmidsi let us know how we can help here ❤️

**Comment by maoueh** [comment]
I see failure:

```
Failed to fetch ABI from Etherscan: invalid json response body at https://api.etherscan.io/api?module=contract&action=getabi&address=0xF87E31492Faf9A91B02Ee0dEAAd50d51d56D5d4d reason: Unexpected token T in JSON at position 0
```

And I have the same in my own PR #991, seems like a problem with the CI itself because it runs fine locally. I imagine the CI is blocked from etherscan APIs.

Maybe we should disable this test?

**Comment by schmidsi** [comment]
@azf20 @evaporei merged. Wen NPM release?

**Comment by evaporei** [comment]
@schmidsi just published in `0.36.0` :wink:

**Pull request merged**
