### PR TITLE
Init command updated to support all hosted-service compatible networks

### PR DESCRIPTION
**Pull request by fordN**
Add `graph init ...` support for `poa-sokol`, `xdai`, `matic`, mumbai, `fantom`, `bsc`, and `clover`.

### CODE REVIEW

**Comment by leoyvens** [comment]
If Etherscan does not support the network, what happens?

**Comment by fordN** [comment]
> If Etherscan does not support the network, what happens?

I believe it continues without an ABI if it can't pull it from etherscan.  In which case the user will simply have to supply it themselves. I'll double check.

**Review by leoyvens — APPROVED** [review]

**Comment by leoyvens** [comment]
@fordN sounds good then

**Comment by AthaSSiN** [comment]
Wanted to ask if there is/will be no support for fetching the ABIs of Matic/Mumbai from Blockscout. (Matic's docs)[https://docs.matic.network/docs/develop/graph/] say that the graph can scan on Blockscout as well, but for me, graph only checks on etherscan (and Matic is not available on etherscan)

**Pull request merged**
